- name: Test connectivity
  hosts: mynginx
  tasks:
  - name: Check if file exists
    stat: 
      path: /tmp/assets.zip
    register: f
  - name: Display the output of stat
    debug:
      msg: "File exists? {{ f.stat.exists }}"
  - name: Upload File
    copy:
      src: assets.zip
      dest: /tmp
    when: not f.stat.exists
  - name: Generate report for list of installed packages
    template:
      src: packages_installed.txt.j2
      dest: packages_installed.txt

  # Installing code-server
  - name: Ensure installation directory (code-server) exists
    file:
      path: "/usr/local/opt/code-server"
      state: directory
      mode: '0755'
  - name: Check setup
    stat:
      path: /usr/lib/code-server
    register: a
  - name: Download Code-Server using wget
    command: wget -O /tmp/code-server.tar.gz https://github.com/coder/code-server/releases/download/v4.96.4/code-server-4.96.4-linux-amd64.tar.gz
  
  - name: Extract Code-Server into /usr/local/opt/code-server
    unarchive:
        src: "/tmp/code-server.tar.gz"
        dest: "/usr/local/opt/code-server"
        remote_src: yes
        list_files: yes
    register: b

  - name: Create symlink for /usr/lib/code-server and /usr/bin/code-server
    file:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      state: "{{ item.state }}"
    loop:
    - src: "/usr/local/opt/code-server/{{ b.files[0] }}"
      dest: /usr/lib/code-server
      state: link
    - src: "/usr/local/opt/code-server/{{ b.files[0] }}/bin/code-server"
      dest: /usr/bin/code-server
      state: link
  - name: Create directory /var/lib/code-server
    file:
      path: "/var/lib/code-server"
      state: directory
      mode: '0755'
  - name: Create a service file code-server.service in /lib/systemd/system/code-server.service
    template:
      dest: "/lib/systemd/system/code-server.service"
      src: "code-server.service.j2"
      mode: '0644'
  - name: Reload config, restart and enable Code-Server
    systemd:
        daemon_reload: yes
        name: code-server
        enabled: yes
        state: restarted
    
  # Configuring Nginx for code-server
  - name: Create nginx config file /etc/nginx/sites-available/code-server.conf
    template:
      dest: "/etc/nginx/sites-available/code-server.conf"
      src: "code-server.conf.j2"
      mode: '0644'
  - name: Remove existing /etc/nginx/sites-enabled/code-server.conf symlink if it exists
    file:
      path: "/etc/nginx/sites-enabled/code-server.conf"
      state: absent
  - name: Symbolic link 3 -  /etc/nginx/sites-available/code-server.conf to /etc/nginx/sites-enabled/code-server.conf
    shell:
      cmd: "ln -s /etc/nginx/sites-available/code-server.conf /etc/nginx/sites-enabled/code-server.conf"
  - name: Reload config, restart and enable Nginx
    systemd:
        daemon_reload: yes
        name: nginx
        enabled: yes
        state: restarted
        

